# One-vs-Rest Logistic Regression from Scratch using NumPy

In [1]:
import numpy as np

# 1. Prepare the dataset
X = np.array([
    [150, 7],   # Class 0
    [170, 6],   # Class 0
    [120, 8],   # Class 1
    [110, 9],   # Class 1
    [180, 5],   # Class 2
    [200, 4],   # Class 2
])
y = np.array([0, 0, 1, 1, 2, 2])

In [2]:

n_samples, n_features = X.shape
n_classes = len(np.unique(y))

In [3]:

# 2. Sigmoid function
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

# 3. Binary cross-entropy loss
def binary_cross_entropy(y_true, y_pred):
    return -np.mean(y_true * np.log(y_pred + 1e-9) + (1 - y_true) * np.log(1 - y_pred + 1e-9))


In [15]:

# 4. Train one-vs-rest classifiers
def train_ovr(X, y, n_classes, lr=0.0005, epochs=500):
    W_all = []
    b_all = []

    for class_idx in range(n_classes):
        print(f"Training classifier for class {class_idx}...")
        # Convert labels: 1 for current class, 0 for others
        y_binary = (y == class_idx).astype(np.float32)
        print("y_binary:", y_binary)
        # Initialize weights and bias
        W = np.zeros(n_features)
        b = 0

        # Train logistic regression
        for epoch in range(epochs):
            z = X @ W + b
            y_pred = sigmoid(z)

            # Compute gradients
            error = y_pred - y_binary
            dW = X.T @ error / n_samples
            db = np.mean(error)

            # Update weights
            W -= lr * dW
            b -= lr * db
            print("weights:", W, "bias:", b)

        W_all.append(W)
        b_all.append(b)

    return np.array(W_all), np.array(b_all)


In [16]:
# 5. Train OvR model
W_ovr, b_ovr=train_ovr(X, y, n_classes)

Training classifier for class 0...
y_binary: [1. 1. 0. 0. 0. 0.]
weights: [-0.01208333 -0.00054167] bias: -8.333333333333333e-05
weights: [4.53685581e-03 5.12059686e-05] bias: 1.3794089959435704e-05
weights: [-0.02109684 -0.0010099 ] bias: -0.00015363730244106618
weights: [ 2.57536239e-03 -9.25942094e-05] bias: -9.060484250564423e-06
weights: [-0.01743512 -0.00093657] bias: -0.0001414859678151324
weights: [ 0.0043234  -0.00011235] bias: -1.0131130254711478e-05
weights: [-0.02070992 -0.00114996] bias: -0.0001738037608103724
weights: [ 0.00280517 -0.00024048] bias: -3.0325678068563746e-05
weights: [-0.01787152 -0.00110985] bias: -0.0001668761966173787
weights: [ 0.00417267 -0.00027202] bias: -3.356696124421802e-05
weights: [-0.02042716 -0.00129265] bias: -0.00019452462331439612
weights: [ 0.00296874 -0.00038908] bias: -5.187727879849409e-05
weights: [-0.01817355 -0.00127617] bias: -0.00019130884168106884
weights: [ 0.00406002 -0.00042924] bias: -5.66993656376816e-05
weights: [-0.02020912

In [9]:
W_all


array([[-0.01208333, -0.00054167],
       [-0.01958333, -0.00020833],
       [-0.00708333, -0.000875  ]])

In [12]:
W_all

array([[-0.01208333, -0.00054167],
       [-0.01958333, -0.00020833],
       [-0.00708333, -0.000875  ]])

In [17]:

# 6. Predict using OvR
def predict_ovr(X, W_all, b_all):
    logits = X @ W_all.T + b_all  # Shape: (n_samples, n_classes)
    probs = sigmoid(logits)       # Apply sigmoid to each class output
    print("logits:\n", logits)
    print("probs:\n", probs)
    preds = np.argmax(probs, axis=1)
    print("preds:", preds)
    return preds, probs

# 7. Inference
preds, probs = predict_ovr(X, W_ovr, b_ovr)

# print("True Labels:     ", y)
# print("Predicted Labels:", preds)
# print("Probabilities:\n", np.round(probs, 3))


logits:
 [[ 0.51822248 -0.91263652  1.04834483]
 [ 0.61886094 -1.47276051  1.67209121]
 [ 0.37533303 -0.18529011  0.2373359 ]
 [ 0.31694556  0.20761148 -0.19914794]
 [ 0.67724841 -1.8656621   2.10857505]
 [ 0.77788686 -2.4257861   2.73232143]]
probs:
 [[0.62673203 0.28646063 0.74045693]
 [0.64995944 0.18652339 0.84185443]
 [0.592747   0.45380955 0.55905702]
 [0.57857968 0.55171724 0.45037691]
 [0.66312429 0.13404445 0.89173384]
 [0.68522451 0.08122739 0.93890713]]
preds: [2 2 0 0 2 2]


In [ ]:
# === Step 1: Import Libraries ===
import numpy as np
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay, classification_report

In [ ]:


# === Step 2: Load and Preprocess Dataset ===
digits = load_digits()
X = digits.data       # shape: (1797, 64)
y = digits.target     # labels: 0-9

# Normalize pixel values
X = X / 16.0

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:

# === Step 3: Helper Functions ===
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

In [ ]:
def binary_logistic_train(X, y, lr=0.1, epochs=1000):
    m, n = X.shape
    X = np.hstack([np.ones((m, 1)), X])  # Add bias column
    weights = np.zeros(n + 1)

    for _ in range(epochs):
        z = X @ weights
        predictions = sigmoid(z)
        gradient = (1 / m) * (X.T @ (predictions - y))
        weights -= lr * gradient

    return weights


In [ ]:


def binary_logistic_predict(X, weights):
    m = X.shape[0]
    X = np.hstack([np.ones((m, 1)), X])
    return sigmoid(X @ weights)

# === Step 4: One-vs-Rest Training ===
def train_ovr(X, y, num_classes):
    all_weights = []
    for class_label in range(num_classes):
        print(f"Training classifier for class {class_label}...")
        y_binary = (y == class_label).astype(int)
        weights = binary_logistic_train(X, y_binary)
        all_weights.append(weights)
    return np.array(all_weights)

# === Step 5: One-vs-Rest Prediction ===
def predict_ovr(X, all_weights):
    m = X.shape[0]
    X = np.hstack([np.ones((m, 1)), X])
    scores = sigmoid(X @ all_weights.T)  # shape: (m, num_classes)
    return np.argmax(scores, axis=1)

# === Step 6: Train and Evaluate ===
num_classes = len(np.unique(y))
all_weights = train_ovr(X_train, y_train, num_classes)
y_pred = predict_ovr(X_test, all_weights)

accuracy = np.mean(y_pred == y_test)
print(f"\n✅ Test Accuracy: {accuracy:.4f}")

# === Step 7: Evaluation Metrics ===
print("\n📊 Classification Report:")
print(classification_report(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=digits.target_names)
disp.plot(cmap='Blues')
plt.title("Confusion Matrix (OvR Logistic Regression)")
plt.show()
